config/routes.rb
Rails.application.routes.draw do
  

   get "blog/viewstatus"

  get "blog/updatestatus"

  get "blog/savestatus"
  devise_for :users, :path => "userauth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register' }

   root :to => 'blog#viewstatus'

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  $list =nil
  def viewstatus


   if current_user === nil
   	"userauth/login"
   else

   end
   
  end

 
  def updatestatus


  end


  def savestatus
  	 respond_to do |format|

  	 	Status.create(:user_id => current_user.id, :message => params[:status].to_s)
  	 	$list = Status.where("user_id=?",current_user.id)
  	 	redirect_to root_path
  	 	return
  	 	#redirect_to :action => 'viewstatus'
  	 	 #format.json{render :json => 'success', :status => 200}
  	 	 
  	 end

  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/updatestatus.html.erb
<h1>Blog#updatestatus</h1>

  
  <form action="/blog/savestatus">
 Status : <input id="stat" type="text" name="status"><br>
 <input type="submit" value="Submit">
</form>

 
 

app/views/blog/viewstatus.html.erb
<% if current_user != nil %>
<h1>Myblog</h1>
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
    <li>
  <%= link_to('Update status', blog_updatestatus_path, :method => :get) %>        
  </li>

<% end%>

<marquee> Your blog goes here !! </marquee>

<% $list  = Status.where("user_id=?",current_user.id) %>
<% $list.each do |status| %>

<p> <%= status.message %> </p>

<% end %>

<% else %>
<script>
location.href = "/userauth/login";
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>